# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='community',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='population', to='neighbourhood.Neighbourhood'),
        ),
    ]
