# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_auto_20181021_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='population', to='neighbourhood.Neighbourhood'),
        ),
    ]
